### ISSUE TITLE
desktop switcher - screen edges (fitts law) and mousewheel

### ISSUE THREAD

**Issue by dobkeratops** [raspberrypi-ui/lxpanel-stretch#1]
hi,
Currently the panel mostly respects 'fitts law' i.e. if you have the panel on the edge, and you move the mouse to the edge, clicks on the appropriate gadgets (launchers, window-switcher) do get picked up - that's awesome;

however one exception to this is the *desktop switcher*; it would be nice to enable rapid desktop switching on the screen edge, especially if you have a maximised window obscuring the background (where switching is rapidly available via the mousewheel)

it would also be awesome for the switcher to use the mousewheel... this lets you flick between them without having to precisely aim (as you can tell from the other [suggestion](https://github.com/raspberrypi-ui/openbox-stretch/issues/2), I think it's nice to leverage a strong association between the mouse-wheel and desktops .. this brings the window/desktop management closer to the power/intuitive feel of the mac's trackpad gestures, where windows & desktops become second nature

**Comment by spl237** [comment]
We will not be supporting multiple desktops (or mechanisms to switch between them) in the Raspberry Pi Desktop environment. This is one of the first design decisions we took; it was a conscious choice, and it will not be changed.

Users who have a requirement for multiple desktops should have the technical ability to edit configuration files to re-enable the behaviour - it's not difficult.
