### ISSUE TITLE
5ghz WiFi Latency Spikes Every 60 Seconds

### ISSUE THREAD

**Issue by Mushoz** [raspberrypi-ui/lxpanel-stretch#2]
Description:

Every 60 seconds (exact), there is a 100+ms latency lag spike for ~2-3 seconds while connected to 5ghz WiFi. This is evident by pinging your router/access point continuously, and seeing a lag spike once every 60 seconds. This is probably caused by the UI interacting with wpa_supplicant to perform background scans to populate the list of WiFi networks in the UI. My global setting of bgscan="" to disable background scanning in wpa_supplicant.conf seems to be ignored.

This issue is _not_ present on a stock Raspbian Lite installation. Only after installing the raspberrypi-ui-mods package and rebooting into the DE will these issues start. The issue is instantly resolved by killing the lxpanel process.

Steps to reproduce:
1. Install Raspbian Lite
2. Boot the Pi and connect to 5ghz WiFi by configuring wpa_supplicant
3. Pings are fine
4. sudo apt update && sudo apt install raspberrypi-ui-mods
5. Reboot into the DE
6. Pings have a lagspike every 60 seconds
7. kill the lxpanel process
8. Pings are fine again.

**Comment by spl237** [comment]
Yes, that is almost certainly due to the background scanning. There's not a great deal that can be done about it - you need to scan to keep the menu updated; we scan intermittently when the menu is closed so as to minimise the lag before it shows the latest status when opened. (We scan a lot more regularly when the menu is open.)

This is basically intended behaviour, and it has been doing it for 4 years now; it's not going to be changed. If the latency presents a problem, I'd suggest removing the networking plugin from the taskbar - it is responsible for initiating the background scans, so removing it will prevent them.

**Comment by Mushoz** [comment]
I understand that this is intended behavior, and I definitely agree this should be the default. But when wpa_supplicant is explicitly configured to disable background scanning, shouldn't this setting be honored by the GUI as well? Presumably, when background scanning is explicitly disabled, the user probably knows what he is doing. Therefore introducing some delay when opening the menu before the networks are shown isn't bad.

**Comment by Mushoz** [comment]
Alternatively, maybe this should be configurable in the plugin itself. This will also retain the sensible defaults for the average user, while allowing people with the knowledge to change the behavior. Looking at the lxplug-network code, making "DHCPCD_WPA_SCAN_LONG" and/or BG_SCAN configurable should do the trick. Thoughts?

**Comment by spl237** [comment]
It's probably most consistent to make it configurable in the plugin - the plugin ignores any settings in the wpa_supplicant file anyway, so it wouldn't make sense for there to be one setting made in there to which it responds. I'll look at including a config parameter for the plugin as you suggest in the panel configuration file.

**Comment by Mushoz** [comment]
Awesome! For people reading this, for now disabling the network plugin is indeed a working workaround as Simon suggested.

**Comment by spl237** [comment]
Code now added to the lxpanel-network plugin to do this - in the lxpanel config file in the dhcpcdui section, the parameters BgScan and BgScanMenu can be set to the scan interval in seconds; setting either to zero disables that scan. The code is in the lxplug-network repo if you want to check it out and build it yourself - we'll add it to the apt repo in the next batch of releases.

**Comment by Mushoz** [comment]
Awesome! Thank you for your great work :)
